-- MySQL Script generated by MySQL Workbench
-- Fri Dec 15 20:48:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Quizmaster
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Quizmaster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Quizmaster` DEFAULT CHARACTER SET utf8 ;
USE `Quizmaster` ;

-- -----------------------------------------------------
-- Table `Quizmaster`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quizmaster`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `prefix` VARCHAR(10) NULL,
  `surname` VARCHAR(45) NOT NULL,
  `role` SET("Student", "Docent", "Coördinator", "Administrator", "Functioneel Beheerder") NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
COMMENT = '										';


-- -----------------------------------------------------
-- Table `Quizmaster`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quizmaster`.`Course` (
  `idCourse` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `nameCourse` VARCHAR(45) NOT NULL,
  `difficultyCourse` SET("1", "2", "3") NOT NULL,
  PRIMARY KEY (`idCourse`),
  INDEX `verzinzelf3_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `verzinzelf3`
    FOREIGN KEY (`idUser`)
    REFERENCES `Quizmaster`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quizmaster`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quizmaster`.`Quiz` (
  `idQuiz` INT NOT NULL AUTO_INCREMENT,
  `idCourse` INT NOT NULL,
  `nameQuiz` VARCHAR(45) NOT NULL,
  `levelQuiz` SET("1", "2", "3") NOT NULL,
  `amountQuestion` INT NOT NULL,
  PRIMARY KEY (`idQuiz`),
  INDEX `verzinzelf1_idx` (`idCourse` ASC) VISIBLE,
  CONSTRAINT `is part of`
    FOREIGN KEY (`idCourse`)
    REFERENCES `Quizmaster`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quizmaster`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quizmaster`.`Question` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `idQuiz` INT NOT NULL,
  `question` VARCHAR(200) NOT NULL,
  `answerGood` VARCHAR(200) NOT NULL,
  `answerWrong1` VARCHAR(200) NOT NULL,
  `answerWrong2` VARCHAR(200) NOT NULL,
  `answerWrong3` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idQuestion`),
  INDEX `verzinzelf4_idx` (`idQuiz` ASC) VISIBLE,
  CONSTRAINT `verzinzelf4`
    FOREIGN KEY (`idQuiz`)
    REFERENCES `Quizmaster`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `Quizmaster`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quizmaster`.`Group` (
  `idGroep` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `nameGroup` VARCHAR(45) NOT NULL,
  `amountStudent` INT NOT NULL,
  PRIMARY KEY (`idGroep`),
  INDEX `verzinzelf2_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `verzinzelf2`
    FOREIGN KEY (`idUser`)
    REFERENCES `Quizmaster`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quizmaster`.`Participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quizmaster`.`Participation` (
  `idUser` INT NOT NULL,
  `idCourse` INT NOT NULL,
  `idGroep` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idCourse`),
  INDEX `verzinzelf6_idx` (`idGroep` ASC) VISIBLE,
  INDEX `verzinzelf5_idx` (`idUser` ASC) VISIBLE,
  INDEX `verzinzelf7_idx` (`idCourse` ASC) VISIBLE,
  CONSTRAINT `verzinzelf5`
    FOREIGN KEY (`idUser`)
    REFERENCES `Quizmaster`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `verzinzelf6`
    FOREIGN KEY (`idGroep`)
    REFERENCES `Quizmaster`.`Group` (`idGroep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `verzinzelf7`
    FOREIGN KEY (`idCourse`)
    REFERENCES `Quizmaster`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
